### ISSUE TITLE
Minecraft Version

### ISSUE THREAD

**Issue by BellCocoa** [Seaoftrees08/SpigotBuilder#1]
Minecraft Versionの順序を直してください。
![image](https://user-images.githubusercontent.com/36551213/78656256-11938f00-7902-11ea-9705-f9a3af769b53.png)

**Comment by Seaoftrees08** [comment]
ソート機能がなく、バージョンがバラバラなのは仕様でした。
先ほどのアップデートでソート機能を追加させていただきました。
これで順序が治るはずです。
